@baseUrl = http://localhost:3000
@token = 

### List all ingredients
GET {{baseUrl}}/api/ingredients
Authorization: Bearer {{token}}

### List ingredients by meal id
GET {{baseUrl}}/api/ingredients/meal/1
Authorization: Bearer {{token}}

### Create ingredient (admin/manager only)
POST {{baseUrl}}/api/ingredients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "mealId": 1,
  "fridgeItemId": 12,
  "amountOfIngredient": 0.1
}

### Update ingredient (admin/manager only)
PATCH {{baseUrl}}/api/ingredients/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "amountOfIngredient": 0.2
}

### Delete ingredient (admin/manager only)
DELETE {{baseUrl}}/api/ingredients/1
Authorization: Bearer {{token}}
