@baseUrl = http://localhost:3000
@token = 

### List all schedules
GET {{baseUrl}}/api/schedules
Authorization: Bearer {{token}}

### Create schedule
POST {{baseUrl}}/api/schedules
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "usersId": 9,
  "workHoursId": 1,
  "isAccepted": false
}

### Get my schedules
GET {{baseUrl}}/api/schedules/my
Authorization: Bearer {{token}}

### Get schedules for user (admin/manager only)
GET {{baseUrl}}/api/schedules/users/1
Authorization: Bearer {{token}}

### Approve schedule (admin/manager only)
PATCH {{baseUrl}}/api/schedules/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "isAccepted": true
}

### Delete schedule (admin/manager only)
DELETE {{baseUrl}}/api/schedules/1
Authorization: Bearer {{token}}
