module.exports.Data = {

    Users:
        [
            { "_id": 1, "name": "Daniel Kovacs", "email": "daniel.kovacs@tablewise.local", "password": "Admin123!", "role": "admin" },
            { "_id": 2, "name": "Eszter Nagy", "email": "eszter.nagy@tablewise.local", "password": "Eszter123!", "role": "manager" },
            { "_id": 3, "name": "Adam Toth", "email": "adam.toth@tablewise.local", "password": "Adam123!", "role": "employee" },
            { "_id": 4, "name": "Lilla Farkas", "email": "lilla.farkas@tablewise.local", "password": "Lilla123!", "role": "employee" },
            { "_id": 5, "name": "Bence Szabo", "email": "bence.szabo@tablewise.local", "password": "Bence123!", "role": "employee" },
            { "_id": 6, "name": "Reka Varga", "email": "reka.varga@tablewise.local", "password": "Reka123!", "role": "employee" },
            { "_id": 7, "name": "Marton Kiss", "email": "marton.kiss@tablewise.local", "password": "Marton123!", "role": "employee" },
            { "_id": 8, "name": "Noemi Horvath", "email": "noemi.horvath@tablewise.local", "password": "Noemi123!", "role": "employee" },
            { "_id": 9, "name": "Zsombor Molnar", "email": "zsombor.molnar@tablewise.local", "password": "Zsombor123!", "role": "employee" },
            { "_id": 10, "name": "Petra Balogh", "email": "petra.balogh@tablewise.local", "password": "Petra123!", "role": "employee" }
        ],

    WorkSchedules:
        [
            { "_id": 1, "usersId": 1, "workHoursId": 1, "isAccepted": true },
            { "_id": 2, "usersId": 2, "workHoursId": 1, "isAccepted": true },
            { "_id": 3, "usersId": 3, "workHoursId": 2, "isAccepted": true },
            { "_id": 4, "usersId": 4, "workHoursId": 2, "isAccepted": false },
            { "_id": 5, "usersId": 5, "workHoursId": 3, "isAccepted": true },
            { "_id": 6, "usersId": 6, "workHoursId": 3, "isAccepted": true },
            { "_id": 7, "usersId": 7, "workHoursId": 4, "isAccepted": true },
            { "_id": 8, "usersId": 8, "workHoursId": 5, "isAccepted": true },
            { "_id": 9, "usersId": 9, "workHoursId": 6, "isAccepted": false },
            { "_id": 10, "usersId": 10, "workHoursId": 7, "isAccepted": true }
        ],

    WorkHours:
        [
            { "_id": 1, "startDate": "2026-03-10T08:00:00Z", "endDate": "2026-03-10T16:00:00Z" },
            { "_id": 2, "startDate": "2026-03-10T16:00:00Z", "endDate": "2026-03-11T00:00:00Z" },
            { "_id": 3, "startDate": "2026-03-11T08:00:00Z", "endDate": "2026-03-11T16:00:00Z" },
            { "_id": 4, "startDate": "2026-03-11T16:00:00Z", "endDate": "2026-03-12T00:00:00Z" },
            { "_id": 5, "startDate": "2026-03-12T08:00:00Z", "endDate": "2026-03-12T16:00:00Z" }
        ],

    Meals:
        [

            { "name": "Bruschetta", "price": 1200, "isAvailable": true, "categoryId": 1, "image": "bruschetta.png" },
            { "name": "Tomato Soup", "price": 1100, "isAvailable": true, "categoryId": 2, "image": "tomato-soup.png" },
            { "name": "Grilled Chicken", "price": 3500, "isAvailable": true, "categoryId": 3, "image": "grilled-chicken.png" },
            { "name": "Pizza Margherita", "price": 2800, "isAvailable": true, "categoryId": 4, "image": "pizza-margherita.png" },
            { "name": "Pasta Carbonara", "price": 3100, "isAvailable": true, "categoryId": 5, "image": "pasta-carbonara.png" },
            { "name": "Greek Salad", "price": 2200, "isAvailable": true, "categoryId": 6, "image": "greek-salad.png" },
            { "name": "Tiramisu", "price": 1500, "isAvailable": true, "categoryId": 7, "image": "tiramisu.png" },
            { "name": "Espresso", "price": 600, "isAvailable": true, "categoryId": 8, "image": "espresso.png" },
            { "name": "French Fries", "price": 900, "isAvailable": true, "categoryId": 9, "image": "french-fries.png" },
            { "name": "Small Pizza", "price": 1800, "isAvailable": true, "categoryId": 10, "image": "small-pizza.png" },
            { "name": "Garlic Bread", "price": 1000, "isAvailable": true, "categoryId": 1, "image": "garlic-bread.png" },
            { "name": "Stuffed Mushrooms", "price": 1450, "isAvailable": true, "categoryId": 1, "image": "stuffed-mushrooms.png" },
            { "name": "Caprese Skewers", "price": 1350, "isAvailable": true, "categoryId": 1, "image": "caprese-skewers.png" },
            { "name": "Crispy Calamari", "price": 2100, "isAvailable": true, "categoryId": 1, "image": "crispy-calamari.png" },
            { "name": "Spinach Dip", "price": 1600, "isAvailable": true, "categoryId": 1, "image": "spinach-dip.png" },
            { "name": "Onion Rings", "price": 950, "isAvailable": true, "categoryId": 1, "image": "onion-rings.png" },
            { "name": "Mozzarella Sticks", "price": 1400, "isAvailable": true, "categoryId": 1, "image": "mozzarella-sticks.png" },
            { "name": "Chicken Wings", "price": 1900, "isAvailable": true, "categoryId": 1, "image": "chicken-wings.png" },
            { "name": "Nacho Platter", "price": 1750, "isAvailable": true, "categoryId": 1, "image": "nacho-platter.png" },
            { "name": "Mushroom Soup", "price": 1200, "isAvailable": true, "categoryId": 2, "image": "mushroom-soup.png" },
            { "name": "Chicken Noodle Soup", "price": 1350, "isAvailable": true, "categoryId": 2, "image": "chicken-noodle-soup.png" },
            { "name": "Cream of Broccoli Soup", "price": 1300, "isAvailable": true, "categoryId": 2, "image": "cream-of-broccoli-soup.png" },
            { "name": "French Onion Soup", "price": 1450, "isAvailable": true, "categoryId": 2, "image": "french-onion-soup.png" },
            { "name": "Pumpkin Soup", "price": 1250, "isAvailable": true, "categoryId": 2, "image": "pumpkin-soup.png" },
            { "name": "Lentil Soup", "price": 1150, "isAvailable": true, "categoryId": 2, "image": "lentil-soup.png" },
            { "name": "Seafood Chowder", "price": 1800, "isAvailable": true, "categoryId": 2, "image": "seafood-chowder.png" },
            { "name": "Goulash Soup", "price": 1550, "isAvailable": true, "categoryId": 2, "image": "goulash-soup.png" },
            { "name": "Vegetable Soup", "price": 1100, "isAvailable": true, "categoryId": 2, "image": "vegetable-soup.png" },
            { "name": "Beef Stroganoff", "price": 3600, "isAvailable": true, "categoryId": 3, "image": "beef-stroganoff.png" },
            { "name": "Roast Duck", "price": 4200, "isAvailable": true, "categoryId": 3, "image": "roast-duck.png" },
            { "name": "BBQ Ribs", "price": 3900, "isAvailable": true, "categoryId": 3, "image": "bbq-ribs.png" },
            { "name": "Salmon Fillet", "price": 4100, "isAvailable": true, "categoryId": 3, "image": "salmon-fillet.png" },
            { "name": "Chicken Parmesan", "price": 3400, "isAvailable": true, "categoryId": 3, "image": "chicken-parmesan.png" },
            { "name": "Pork Schnitzel", "price": 3200, "isAvailable": true, "categoryId": 3, "image": "pork-schnitzel.png" },
            { "name": "Lamb Chops", "price": 4600, "isAvailable": true, "categoryId": 3, "image": "lamb-chops.png" },
            { "name": "Stuffed Peppers", "price": 2950, "isAvailable": true, "categoryId": 3, "image": "stuffed-peppers.png" },
            { "name": "Fish and Chips", "price": 3000, "isAvailable": true, "categoryId": 3, "image": "fish-and-chips.png" },
            { "name": "Pepperoni Pizza", "price": 2950, "isAvailable": true, "categoryId": 4, "image": "pepperoni-pizza.png" },
            { "name": "Four Cheese Pizza", "price": 3150, "isAvailable": true, "categoryId": 4, "image": "four-cheese-pizza.png" },
            { "name": "Hawaiian Pizza", "price": 3050, "isAvailable": true, "categoryId": 4, "image": "hawaiian-pizza.png" },
            { "name": "Vegetarian Pizza", "price": 2850, "isAvailable": true, "categoryId": 4, "image": "vegetarian-pizza.png" },
            { "name": "BBQ Chicken Pizza", "price": 3300, "isAvailable": true, "categoryId": 4, "image": "bbq-chicken-pizza.png" },
            { "name": "Diavola Pizza", "price": 3200, "isAvailable": true, "categoryId": 4, "image": "diavola-pizza.png" },
            { "name": "Prosciutto Pizza", "price": 3350, "isAvailable": true, "categoryId": 4, "image": "prosciutto-pizza.png" },
            { "name": "Seafood Pizza", "price": 3600, "isAvailable": true, "categoryId": 4, "image": "seafood-pizza.png" },
            { "name": "Mushroom Pizza", "price": 2900, "isAvailable": true, "categoryId": 4, "image": "mushroom-pizza.png" },
            { "name": "Penne Arrabbiata", "price": 2600, "isAvailable": true, "categoryId": 5, "image": "penne-arrabbiata.png" },
            { "name": "Spaghetti Bolognese", "price": 2900, "isAvailable": true, "categoryId": 5, "image": "spaghetti-bolognese.png" },
            { "name": "Fettuccine Alfredo", "price": 3000, "isAvailable": true, "categoryId": 5, "image": "fettuccine-alfredo.png" },
            { "name": "Lasagna al Forno", "price": 3200, "isAvailable": true, "categoryId": 5, "image": "lasagna-al-forno.png" },
            { "name": "Pesto Linguine", "price": 2850, "isAvailable": true, "categoryId": 5, "image": "pesto-linguine.png" },
            { "name": "Seafood Tagliatelle", "price": 3550, "isAvailable": true, "categoryId": 5, "image": "seafood-tagliatelle.png" },
            { "name": "Baked Mac and Cheese", "price": 2500, "isAvailable": true, "categoryId": 5, "image": "baked-mac-and-cheese.png" },
            { "name": "Mushroom Ravioli", "price": 3100, "isAvailable": true, "categoryId": 5, "image": "mushroom-ravioli.png" },
            { "name": "Spinach Ricotta Cannelloni", "price": 3250, "isAvailable": true, "categoryId": 5, "image": "spinach-ricotta-cannelloni.png" },
            { "name": "Caesar Salad", "price": 2300, "isAvailable": true, "categoryId": 6, "image": "caesar-salad.png" },
            { "name": "Cobb Salad", "price": 2500, "isAvailable": true, "categoryId": 6, "image": "cobb-salad.png" },
            { "name": "Garden Salad", "price": 1800, "isAvailable": true, "categoryId": 6, "image": "garden-salad.png" },
            { "name": "Tuna Salad", "price": 2400, "isAvailable": true, "categoryId": 6, "image": "tuna-salad.png" },
            { "name": "Chicken Avocado Salad", "price": 2700, "isAvailable": true, "categoryId": 6, "image": "chicken-avocado-salad.png" },
            { "name": "Quinoa Salad", "price": 2350, "isAvailable": true, "categoryId": 6, "image": "quinoa-salad.png" },
            { "name": "Beetroot Salad", "price": 2100, "isAvailable": true, "categoryId": 6, "image": "beetroot-salad.png" },
            { "name": "Shrimp Salad", "price": 2900, "isAvailable": true, "categoryId": 6, "image": "shrimp-salad.png" },
            { "name": "Mediterranean Salad", "price": 2250, "isAvailable": true, "categoryId": 6, "image": "mediterranean-salad.png" },
            { "name": "Chocolate Lava Cake", "price": 1700, "isAvailable": true, "categoryId": 7, "image": "chocolate-lava-cake.png" },
            { "name": "Cheesecake", "price": 1650, "isAvailable": true, "categoryId": 7, "image": "cheesecake.png" },
            { "name": "Apple Pie", "price": 1500, "isAvailable": true, "categoryId": 7, "image": "apple-pie.png" },
            { "name": "Panna Cotta", "price": 1550, "isAvailable": true, "categoryId": 7, "image": "panna-cotta.png" },
            { "name": "Brownie Sundae", "price": 1750, "isAvailable": true, "categoryId": 7, "image": "brownie-sundae.png" },
            { "name": "Creme Brulee", "price": 1800, "isAvailable": true, "categoryId": 7, "image": "creme-brulee.png" },
            { "name": "Lemon Tart", "price": 1600, "isAvailable": true, "categoryId": 7, "image": "lemon-tart.png" },
            { "name": "Ice Cream Trio", "price": 1450, "isAvailable": true, "categoryId": 7, "image": "ice-cream-trio.png" },
            { "name": "Chocolate Mousse", "price": 1580, "isAvailable": true, "categoryId": 7, "image": "chocolate-mousse.png" },
            { "name": "Americano", "price": 700, "isAvailable": true, "categoryId": 8, "image": "americano.png" },
            { "name": "Cappuccino", "price": 850, "isAvailable": true, "categoryId": 8, "image": "cappuccino.png" },
            { "name": "Latte", "price": 900, "isAvailable": true, "categoryId": 8, "image": "latte.png" },
            { "name": "Hot Chocolate", "price": 950, "isAvailable": true, "categoryId": 8, "image": "hot-chocolate.png" },
            { "name": "Orange Juice", "price": 800, "isAvailable": true, "categoryId": 8, "image": "orange-juice.png" },
            { "name": "Lemonade", "price": 780, "isAvailable": true, "categoryId": 8, "image": "lemonade.png" },
            { "name": "Iced Tea", "price": 760, "isAvailable": true, "categoryId": 8, "image": "iced-tea.png" },
            { "name": "Mineral Water", "price": 450, "isAvailable": true, "categoryId": 8, "image": "mineral-water.png" },
            { "name": "Berry Smoothie", "price": 1200, "isAvailable": true, "categoryId": 8, "image": "berry-smoothie.png" },
            { "name": "Sweet Potato Fries", "price": 1100, "isAvailable": true, "categoryId": 9, "image": "sweet-potato-fries.png" },
            { "name": "Mashed Potatoes", "price": 950, "isAvailable": true, "categoryId": 9, "image": "mashed-potatoes.png" },
            { "name": "Steamed Rice", "price": 700, "isAvailable": true, "categoryId": 9, "image": "steamed-rice.png" },
            { "name": "Grilled Vegetables", "price": 1200, "isAvailable": true, "categoryId": 9, "image": "grilled-vegetables.png" },
            { "name": "Coleslaw", "price": 650, "isAvailable": true, "categoryId": 9, "image": "coleslaw.png" },
            { "name": "Mac and Cheese Bites", "price": 1300, "isAvailable": true, "categoryId": 9, "image": "mac-and-cheese-bites.png" },
            { "name": "Garlic Mashed Cauliflower", "price": 1050, "isAvailable": true, "categoryId": 9, "image": "garlic-mashed-cauliflower.png" },
            { "name": "Buttered Corn", "price": 750, "isAvailable": true, "categoryId": 9, "image": "buttered-corn.png" },
            { "name": "Side Caesar Salad", "price": 990, "isAvailable": true, "categoryId": 9, "image": "side-caesar-salad.png" },
            { "name": "Mini Cheeseburger", "price": 1900, "isAvailable": true, "categoryId": 10, "image": "mini-cheeseburger.png" },
            { "name": "Kids Chicken Nuggets", "price": 1700, "isAvailable": true, "categoryId": 10, "image": "kids-chicken-nuggets.png" },
            { "name": "Mini Spaghetti", "price": 1600, "isAvailable": true, "categoryId": 10, "image": "mini-spaghetti.png" },
            { "name": "Kids Mac and Cheese", "price": 1500, "isAvailable": true, "categoryId": 10, "image": "kids-mac-and-cheese.png" },
            { "name": "Mini Pancakes", "price": 1400, "isAvailable": true, "categoryId": 10, "image": "mini-pancakes.png" },
            { "name": "Kids Fish Fingers", "price": 1750, "isAvailable": true, "categoryId": 10, "image": "kids-fish-fingers.png" },
            { "name": "Mini Quesadilla", "price": 1650, "isAvailable": true, "categoryId": 10, "image": "mini-quesadilla.png" },
            { "name": "Kids Pasta Alfredo", "price": 1550, "isAvailable": true, "categoryId": 10, "image": "kids-pasta-alfredo.png" },
            { "name": "Mini Hot Dog", "price": 1450, "isAvailable": true, "categoryId": 10, "image": "mini-hot-dog.png" }
        ],

    MealCategories:
        [
            { "_id": 1, "name": "Appetizers" },
            { "_id": 2, "name": "Soups" },
            { "_id": 3, "name": "Main Courses" },
            { "_id": 4, "name": "Pizzas" },
            { "_id": 5, "name": "Pastas" },
            { "_id": 6, "name": "Salads" },
            { "_id": 7, "name": "Desserts" },
            { "_id": 8, "name": "Beverages" },
            { "_id": 9, "name": "Sides" },
            { "_id": 10, "name": "Kids Menu" }
        ],

    Ingredients:
        [
            { "_id": 1, "mealId": 1, "fridgeItemId": 1, "amountOfIngredient": 0.2 },
            { "_id": 2, "mealId": 1, "fridgeItemId": 11, "amountOfIngredient": 0.05 },
            { "_id": 3, "mealId": 1, "fridgeItemId": 6, "amountOfIngredient": 0.03 },
            { "_id": 4, "mealId": 2, "fridgeItemId": 8, "amountOfIngredient": 0.2 },
            { "_id": 5, "mealId": 2, "fridgeItemId": 20, "amountOfIngredient": 0.4 },
            { "_id": 6, "mealId": 2, "fridgeItemId": 16, "amountOfIngredient": 0.1 },
            { "_id": 7, "mealId": 3, "fridgeItemId": 3, "amountOfIngredient": 0.35 },
            { "_id": 8, "mealId": 3, "fridgeItemId": 4, "amountOfIngredient": 0.01 },
            { "_id": 9, "mealId": 3, "fridgeItemId": 6, "amountOfIngredient": 0.02 },
            { "_id": 10, "mealId": 4, "fridgeItemId": 5, "amountOfIngredient": 0.25 },
            { "_id": 11, "mealId": 4, "fridgeItemId": 2, "amountOfIngredient": 0.2 },
            { "_id": 12, "mealId": 4, "fridgeItemId": 33, "amountOfIngredient": 0.12 },
            { "_id": 13, "mealId": 5, "fridgeItemId": 35, "amountOfIngredient": 0.18 },
            { "_id": 14, "mealId": 5, "fridgeItemId": 32, "amountOfIngredient": 0.08 },
            { "_id": 15, "mealId": 5, "fridgeItemId": 71, "amountOfIngredient": 0.08 },
            { "_id": 16, "mealId": 6, "fridgeItemId": 1, "amountOfIngredient": 0.15 },
            { "_id": 17, "mealId": 6, "fridgeItemId": 39, "amountOfIngredient": 0.12 },
            { "_id": 18, "mealId": 6, "fridgeItemId": 6, "amountOfIngredient": 0.02 },
            { "_id": 19, "mealId": 7, "fridgeItemId": 44, "amountOfIngredient": 0.12 },
            { "_id": 20, "mealId": 7, "fridgeItemId": 47, "amountOfIngredient": 0.02 },
            { "_id": 21, "mealId": 7, "fridgeItemId": 45, "amountOfIngredient": 0.02 },
            { "_id": 22, "mealId": 8, "fridgeItemId": 47, "amountOfIngredient": 0.02 },
            { "_id": 23, "mealId": 9, "fridgeItemId": 30, "amountOfIngredient": 0.3 },
            { "_id": 24, "mealId": 9, "fridgeItemId": 6, "amountOfIngredient": 0.03 },
            { "_id": 25, "mealId": 10, "fridgeItemId": 5, "amountOfIngredient": 0.18 },
            { "_id": 26, "mealId": 10, "fridgeItemId": 2, "amountOfIngredient": 0.12 },
            { "_id": 27, "mealId": 10, "fridgeItemId": 33, "amountOfIngredient": 0.08 },
            { "_id": 28, "mealId": 11, "fridgeItemId": 5, "amountOfIngredient": 0.15 },
            { "_id": 29, "mealId": 11, "fridgeItemId": 12, "amountOfIngredient": 0.03 },
            { "_id": 30, "mealId": 11, "fridgeItemId": 63, "amountOfIngredient": 0.04 },
            { "_id": 31, "mealId": 12, "fridgeItemId": 13, "amountOfIngredient": 0.2 },
            { "_id": 32, "mealId": 12, "fridgeItemId": 32, "amountOfIngredient": 0.05 },
            { "_id": 33, "mealId": 12, "fridgeItemId": 12, "amountOfIngredient": 0.02 },
            { "_id": 34, "mealId": 13, "fridgeItemId": 1, "amountOfIngredient": 0.12 },
            { "_id": 35, "mealId": 13, "fridgeItemId": 2, "amountOfIngredient": 0.12 },
            { "_id": 36, "mealId": 13, "fridgeItemId": 11, "amountOfIngredient": 0.03 },
            { "_id": 37, "mealId": 14, "fridgeItemId": 14, "amountOfIngredient": 0.25 },
            { "_id": 38, "mealId": 14, "fridgeItemId": 66, "amountOfIngredient": 0.08 },
            { "_id": 39, "mealId": 14, "fridgeItemId": 6, "amountOfIngredient": 0.03 },
            { "_id": 40, "mealId": 15, "fridgeItemId": 15, "amountOfIngredient": 0.18 },
            { "_id": 41, "mealId": 15, "fridgeItemId": 18, "amountOfIngredient": 0.1 },
            { "_id": 42, "mealId": 15, "fridgeItemId": 12, "amountOfIngredient": 0.02 },
            { "_id": 43, "mealId": 16, "fridgeItemId": 16, "amountOfIngredient": 0.22 },
            { "_id": 44, "mealId": 16, "fridgeItemId": 5, "amountOfIngredient": 0.08 },
            { "_id": 45, "mealId": 16, "fridgeItemId": 6, "amountOfIngredient": 0.03 },
            { "_id": 46, "mealId": 17, "fridgeItemId": 2, "amountOfIngredient": 0.18 },
            { "_id": 47, "mealId": 17, "fridgeItemId": 66, "amountOfIngredient": 0.08 },
            { "_id": 48, "mealId": 17, "fridgeItemId": 5, "amountOfIngredient": 0.05 },
            { "_id": 49, "mealId": 18, "fridgeItemId": 3, "amountOfIngredient": 0.25 },
            { "_id": 50, "mealId": 18, "fridgeItemId": 4, "amountOfIngredient": 0.01 },
            { "_id": 51, "mealId": 18, "fridgeItemId": 6, "amountOfIngredient": 0.02 },
            { "_id": 52, "mealId": 19, "fridgeItemId": 19, "amountOfIngredient": 0.2 },
            { "_id": 53, "mealId": 19, "fridgeItemId": 17, "amountOfIngredient": 0.12 },
            { "_id": 54, "mealId": 19, "fridgeItemId": 1, "amountOfIngredient": 0.1 },
            { "_id": 55, "mealId": 20, "fridgeItemId": 13, "amountOfIngredient": 0.18 },
            { "_id": 56, "mealId": 20, "fridgeItemId": 20, "amountOfIngredient": 0.35 },
            { "_id": 57, "mealId": 20, "fridgeItemId": 46, "amountOfIngredient": 0.08 },
            { "_id": 58, "mealId": 21, "fridgeItemId": 3, "amountOfIngredient": 0.2 },
            { "_id": 59, "mealId": 21, "fridgeItemId": 20, "amountOfIngredient": 0.4 },
            { "_id": 60, "mealId": 21, "fridgeItemId": 16, "amountOfIngredient": 0.08 },
            { "_id": 61, "mealId": 22, "fridgeItemId": 21, "amountOfIngredient": 0.2 },
            { "_id": 62, "mealId": 22, "fridgeItemId": 46, "amountOfIngredient": 0.08 },
            { "_id": 63, "mealId": 22, "fridgeItemId": 20, "amountOfIngredient": 0.35 },
            { "_id": 64, "mealId": 23, "fridgeItemId": 16, "amountOfIngredient": 0.25 },
            { "_id": 65, "mealId": 23, "fridgeItemId": 20, "amountOfIngredient": 0.35 },
            { "_id": 66, "mealId": 23, "fridgeItemId": 63, "amountOfIngredient": 0.03 },
            { "_id": 67, "mealId": 24, "fridgeItemId": 22, "amountOfIngredient": 0.25 },
            { "_id": 68, "mealId": 24, "fridgeItemId": 46, "amountOfIngredient": 0.08 },
            { "_id": 69, "mealId": 24, "fridgeItemId": 20, "amountOfIngredient": 0.35 },
            { "_id": 70, "mealId": 25, "fridgeItemId": 23, "amountOfIngredient": 0.2 },
            { "_id": 71, "mealId": 25, "fridgeItemId": 16, "amountOfIngredient": 0.08 },
            { "_id": 72, "mealId": 25, "fridgeItemId": 20, "amountOfIngredient": 0.35 },
            { "_id": 73, "mealId": 26, "fridgeItemId": 24, "amountOfIngredient": 0.22 },
            { "_id": 74, "mealId": 26, "fridgeItemId": 46, "amountOfIngredient": 0.1 },
            { "_id": 75, "mealId": 26, "fridgeItemId": 20, "amountOfIngredient": 0.35 },
            { "_id": 76, "mealId": 27, "fridgeItemId": 25, "amountOfIngredient": 0.22 },
            { "_id": 77, "mealId": 27, "fridgeItemId": 73, "amountOfIngredient": 0.12 },
            { "_id": 78, "mealId": 27, "fridgeItemId": 16, "amountOfIngredient": 0.08 },
            { "_id": 79, "mealId": 28, "fridgeItemId": 1, "amountOfIngredient": 0.12 },
            { "_id": 80, "mealId": 28, "fridgeItemId": 68, "amountOfIngredient": 0.12 },
            { "_id": 81, "mealId": 28, "fridgeItemId": 20, "amountOfIngredient": 0.35 },
            { "_id": 82, "mealId": 29, "fridgeItemId": 25, "amountOfIngredient": 0.25 },
            { "_id": 83, "mealId": 29, "fridgeItemId": 13, "amountOfIngredient": 0.15 },
            { "_id": 84, "mealId": 29, "fridgeItemId": 18, "amountOfIngredient": 0.07 },
            { "_id": 85, "mealId": 30, "fridgeItemId": 26, "amountOfIngredient": 0.3 },
            { "_id": 86, "mealId": 30, "fridgeItemId": 4, "amountOfIngredient": 0.01 },
            { "_id": 87, "mealId": 30, "fridgeItemId": 63, "amountOfIngredient": 0.03 },
            { "_id": 88, "mealId": 31, "fridgeItemId": 27, "amountOfIngredient": 0.3 },
            { "_id": 89, "mealId": 31, "fridgeItemId": 4, "amountOfIngredient": 0.01 },
            { "_id": 90, "mealId": 31, "fridgeItemId": 8, "amountOfIngredient": 0.08 },
            { "_id": 91, "mealId": 32, "fridgeItemId": 29, "amountOfIngredient": 0.28 },
            { "_id": 92, "mealId": 32, "fridgeItemId": 50, "amountOfIngredient": 0.03 },
            { "_id": 93, "mealId": 32, "fridgeItemId": 6, "amountOfIngredient": 0.02 },
            { "_id": 94, "mealId": 33, "fridgeItemId": 3, "amountOfIngredient": 0.28 },
            { "_id": 95, "mealId": 33, "fridgeItemId": 32, "amountOfIngredient": 0.08 },
            { "_id": 96, "mealId": 33, "fridgeItemId": 8, "amountOfIngredient": 0.08 },
            { "_id": 97, "mealId": 34, "fridgeItemId": 27, "amountOfIngredient": 0.28 },
            { "_id": 98, "mealId": 34, "fridgeItemId": 66, "amountOfIngredient": 0.09 },
            { "_id": 99, "mealId": 34, "fridgeItemId": 4, "amountOfIngredient": 0.01 },
            { "_id": 100, "mealId": 35, "fridgeItemId": 28, "amountOfIngredient": 0.3 },
            { "_id": 101, "mealId": 35, "fridgeItemId": 4, "amountOfIngredient": 0.01 },
            { "_id": 102, "mealId": 35, "fridgeItemId": 6, "amountOfIngredient": 0.02 },
            { "_id": 103, "mealId": 36, "fridgeItemId": 73, "amountOfIngredient": 0.25 },
            { "_id": 104, "mealId": 36, "fridgeItemId": 25, "amountOfIngredient": 0.18 },
            { "_id": 105, "mealId": 36, "fridgeItemId": 16, "amountOfIngredient": 0.08 },
            { "_id": 106, "mealId": 37, "fridgeItemId": 54, "amountOfIngredient": 0.25 },
            { "_id": 107, "mealId": 37, "fridgeItemId": 30, "amountOfIngredient": 0.25 },
            { "_id": 108, "mealId": 37, "fridgeItemId": 66, "amountOfIngredient": 0.07 },
            { "_id": 109, "mealId": 38, "fridgeItemId": 5, "amountOfIngredient": 0.25 },
            { "_id": 110, "mealId": 38, "fridgeItemId": 31, "amountOfIngredient": 0.1 },
            { "_id": 111, "mealId": 38, "fridgeItemId": 2, "amountOfIngredient": 0.18 },
            { "_id": 112, "mealId": 39, "fridgeItemId": 5, "amountOfIngredient": 0.25 },
            { "_id": 113, "mealId": 39, "fridgeItemId": 2, "amountOfIngredient": 0.14 },
            { "_id": 114, "mealId": 39, "fridgeItemId": 17, "amountOfIngredient": 0.12 },
            { "_id": 115, "mealId": 40, "fridgeItemId": 5, "amountOfIngredient": 0.25 },
            { "_id": 116, "mealId": 40, "fridgeItemId": 56, "amountOfIngredient": 0.12 },
            { "_id": 117, "mealId": 40, "fridgeItemId": 2, "amountOfIngredient": 0.18 },
            { "_id": 118, "mealId": 41, "fridgeItemId": 5, "amountOfIngredient": 0.25 },
            { "_id": 119, "mealId": 41, "fridgeItemId": 13, "amountOfIngredient": 0.12 },
            { "_id": 120, "mealId": 41, "fridgeItemId": 15, "amountOfIngredient": 0.1 },
            { "_id": 121, "mealId": 42, "fridgeItemId": 5, "amountOfIngredient": 0.25 },
            { "_id": 122, "mealId": 42, "fridgeItemId": 3, "amountOfIngredient": 0.16 },
            { "_id": 123, "mealId": 42, "fridgeItemId": 2, "amountOfIngredient": 0.16 },
            { "_id": 124, "mealId": 43, "fridgeItemId": 5, "amountOfIngredient": 0.25 },
            { "_id": 125, "mealId": 43, "fridgeItemId": 31, "amountOfIngredient": 0.1 },
            { "_id": 126, "mealId": 43, "fridgeItemId": 33, "amountOfIngredient": 0.12 },
            { "_id": 127, "mealId": 44, "fridgeItemId": 5, "amountOfIngredient": 0.25 },
            { "_id": 128, "mealId": 44, "fridgeItemId": 57, "amountOfIngredient": 0.1 },
            { "_id": 129, "mealId": 44, "fridgeItemId": 2, "amountOfIngredient": 0.16 },
            { "_id": 130, "mealId": 45, "fridgeItemId": 5, "amountOfIngredient": 0.25 },
            { "_id": 131, "mealId": 45, "fridgeItemId": 24, "amountOfIngredient": 0.16 },
            { "_id": 132, "mealId": 45, "fridgeItemId": 2, "amountOfIngredient": 0.16 },
            { "_id": 133, "mealId": 46, "fridgeItemId": 5, "amountOfIngredient": 0.25 },
            { "_id": 134, "mealId": 46, "fridgeItemId": 13, "amountOfIngredient": 0.15 },
            { "_id": 135, "mealId": 46, "fridgeItemId": 2, "amountOfIngredient": 0.16 },
            { "_id": 136, "mealId": 47, "fridgeItemId": 36, "amountOfIngredient": 0.18 },
            { "_id": 137, "mealId": 47, "fridgeItemId": 8, "amountOfIngredient": 0.08 },
            { "_id": 138, "mealId": 47, "fridgeItemId": 12, "amountOfIngredient": 0.02 },
            { "_id": 139, "mealId": 48, "fridgeItemId": 35, "amountOfIngredient": 0.18 },
            { "_id": 140, "mealId": 48, "fridgeItemId": 25, "amountOfIngredient": 0.16 },
            { "_id": 141, "mealId": 48, "fridgeItemId": 8, "amountOfIngredient": 0.08 },
            { "_id": 142, "mealId": 49, "fridgeItemId": 36, "amountOfIngredient": 0.18 },
            { "_id": 143, "mealId": 49, "fridgeItemId": 46, "amountOfIngredient": 0.1 },
            { "_id": 144, "mealId": 49, "fridgeItemId": 32, "amountOfIngredient": 0.08 },
            { "_id": 145, "mealId": 50, "fridgeItemId": 34, "amountOfIngredient": 0.18 },
            { "_id": 146, "mealId": 50, "fridgeItemId": 25, "amountOfIngredient": 0.16 },
            { "_id": 147, "mealId": 50, "fridgeItemId": 2, "amountOfIngredient": 0.12 },
            { "_id": 148, "mealId": 51, "fridgeItemId": 35, "amountOfIngredient": 0.18 },
            { "_id": 149, "mealId": 51, "fridgeItemId": 11, "amountOfIngredient": 0.05 },
            { "_id": 150, "mealId": 51, "fridgeItemId": 6, "amountOfIngredient": 0.03 },
            { "_id": 151, "mealId": 52, "fridgeItemId": 35, "amountOfIngredient": 0.18 },
            { "_id": 152, "mealId": 52, "fridgeItemId": 24, "amountOfIngredient": 0.16 },
            { "_id": 153, "mealId": 52, "fridgeItemId": 12, "amountOfIngredient": 0.02 },
            { "_id": 154, "mealId": 53, "fridgeItemId": 36, "amountOfIngredient": 0.18 },
            { "_id": 155, "mealId": 53, "fridgeItemId": 17, "amountOfIngredient": 0.16 },
            { "_id": 156, "mealId": 53, "fridgeItemId": 48, "amountOfIngredient": 0.1 },
            { "_id": 157, "mealId": 54, "fridgeItemId": 34, "amountOfIngredient": 0.16 },
            { "_id": 158, "mealId": 54, "fridgeItemId": 13, "amountOfIngredient": 0.14 },
            { "_id": 159, "mealId": 54, "fridgeItemId": 64, "amountOfIngredient": 0.1 },
            { "_id": 160, "mealId": 55, "fridgeItemId": 34, "amountOfIngredient": 0.16 },
            { "_id": 161, "mealId": 55, "fridgeItemId": 15, "amountOfIngredient": 0.14 },
            { "_id": 162, "mealId": 55, "fridgeItemId": 64, "amountOfIngredient": 0.12 },
            { "_id": 163, "mealId": 56, "fridgeItemId": 38, "amountOfIngredient": 0.16 },
            { "_id": 164, "mealId": 56, "fridgeItemId": 3, "amountOfIngredient": 0.12 },
            { "_id": 165, "mealId": 56, "fridgeItemId": 32, "amountOfIngredient": 0.05 },
            { "_id": 166, "mealId": 57, "fridgeItemId": 38, "amountOfIngredient": 0.14 },
            { "_id": 167, "mealId": 57, "fridgeItemId": 3, "amountOfIngredient": 0.12 },
            { "_id": 168, "mealId": 57, "fridgeItemId": 71, "amountOfIngredient": 0.06 },
            { "_id": 169, "mealId": 58, "fridgeItemId": 1, "amountOfIngredient": 0.12 },
            { "_id": 170, "mealId": 58, "fridgeItemId": 39, "amountOfIngredient": 0.12 },
            { "_id": 171, "mealId": 58, "fridgeItemId": 38, "amountOfIngredient": 0.12 },
            { "_id": 172, "mealId": 59, "fridgeItemId": 41, "amountOfIngredient": 0.14 },
            { "_id": 173, "mealId": 59, "fridgeItemId": 38, "amountOfIngredient": 0.12 },
            { "_id": 174, "mealId": 59, "fridgeItemId": 39, "amountOfIngredient": 0.1 },
            { "_id": 175, "mealId": 60, "fridgeItemId": 3, "amountOfIngredient": 0.14 },
            { "_id": 176, "mealId": 60, "fridgeItemId": 40, "amountOfIngredient": 0.12 },
            { "_id": 177, "mealId": 60, "fridgeItemId": 38, "amountOfIngredient": 0.12 },
            { "_id": 178, "mealId": 61, "fridgeItemId": 42, "amountOfIngredient": 0.16 },
            { "_id": 179, "mealId": 61, "fridgeItemId": 39, "amountOfIngredient": 0.1 },
            { "_id": 180, "mealId": 61, "fridgeItemId": 1, "amountOfIngredient": 0.1 },
            { "_id": 181, "mealId": 62, "fridgeItemId": 72, "amountOfIngredient": 0.16 },
            { "_id": 182, "mealId": 62, "fridgeItemId": 38, "amountOfIngredient": 0.1 },
            { "_id": 183, "mealId": 62, "fridgeItemId": 18, "amountOfIngredient": 0.04 },
            { "_id": 184, "mealId": 63, "fridgeItemId": 43, "amountOfIngredient": 0.14 },
            { "_id": 185, "mealId": 63, "fridgeItemId": 38, "amountOfIngredient": 0.12 },
            { "_id": 186, "mealId": 63, "fridgeItemId": 39, "amountOfIngredient": 0.1 },
            { "_id": 187, "mealId": 64, "fridgeItemId": 1, "amountOfIngredient": 0.12 },
            { "_id": 188, "mealId": 64, "fridgeItemId": 39, "amountOfIngredient": 0.12 },
            { "_id": 189, "mealId": 64, "fridgeItemId": 6, "amountOfIngredient": 0.02 },
            { "_id": 190, "mealId": 65, "fridgeItemId": 45, "amountOfIngredient": 0.05 },
            { "_id": 191, "mealId": 65, "fridgeItemId": 63, "amountOfIngredient": 0.06 },
            { "_id": 192, "mealId": 65, "fridgeItemId": 62, "amountOfIngredient": 2 },
            { "_id": 193, "mealId": 66, "fridgeItemId": 58, "amountOfIngredient": 0.16 },
            { "_id": 194, "mealId": 66, "fridgeItemId": 62, "amountOfIngredient": 2 },
            { "_id": 195, "mealId": 66, "fridgeItemId": 61, "amountOfIngredient": 0.05 },
            { "_id": 196, "mealId": 67, "fridgeItemId": 59, "amountOfIngredient": 0.2 },
            { "_id": 197, "mealId": 67, "fridgeItemId": 5, "amountOfIngredient": 0.15 },
            { "_id": 198, "mealId": 67, "fridgeItemId": 63, "amountOfIngredient": 0.08 },
            { "_id": 199, "mealId": 68, "fridgeItemId": 46, "amountOfIngredient": 0.16 },
            { "_id": 200, "mealId": 68, "fridgeItemId": 48, "amountOfIngredient": 0.1 },
            { "_id": 201, "mealId": 68, "fridgeItemId": 65, "amountOfIngredient": 0.01 },
            { "_id": 202, "mealId": 69, "fridgeItemId": 45, "amountOfIngredient": 0.05 },
            { "_id": 203, "mealId": 69, "fridgeItemId": 63, "amountOfIngredient": 0.06 },
            { "_id": 204, "mealId": 69, "fridgeItemId": 70, "amountOfIngredient": 0.12 },
            { "_id": 205, "mealId": 70, "fridgeItemId": 46, "amountOfIngredient": 0.14 },
            { "_id": 206, "mealId": 70, "fridgeItemId": 62, "amountOfIngredient": 2 },
            { "_id": 207, "mealId": 70, "fridgeItemId": 61, "amountOfIngredient": 0.04 },
            { "_id": 208, "mealId": 71, "fridgeItemId": 50, "amountOfIngredient": 0.06 },
            { "_id": 209, "mealId": 71, "fridgeItemId": 63, "amountOfIngredient": 0.07 },
            { "_id": 210, "mealId": 71, "fridgeItemId": 5, "amountOfIngredient": 0.12 },
            { "_id": 211, "mealId": 72, "fridgeItemId": 70, "amountOfIngredient": 0.24 },
            { "_id": 212, "mealId": 72, "fridgeItemId": 52, "amountOfIngredient": 0.06 },
            { "_id": 213, "mealId": 72, "fridgeItemId": 45, "amountOfIngredient": 0.02 },
            { "_id": 214, "mealId": 73, "fridgeItemId": 45, "amountOfIngredient": 0.05 },
            { "_id": 215, "mealId": 73, "fridgeItemId": 46, "amountOfIngredient": 0.12 },
            { "_id": 216, "mealId": 73, "fridgeItemId": 62, "amountOfIngredient": 1 },
            { "_id": 217, "mealId": 74, "fridgeItemId": 47, "amountOfIngredient": 0.02 },
            { "_id": 218, "mealId": 75, "fridgeItemId": 47, "amountOfIngredient": 0.02 },
            { "_id": 219, "mealId": 75, "fridgeItemId": 48, "amountOfIngredient": 0.18 },
            { "_id": 220, "mealId": 76, "fridgeItemId": 47, "amountOfIngredient": 0.02 },
            { "_id": 221, "mealId": 76, "fridgeItemId": 48, "amountOfIngredient": 0.22 },
            { "_id": 222, "mealId": 77, "fridgeItemId": 45, "amountOfIngredient": 0.04 },
            { "_id": 223, "mealId": 77, "fridgeItemId": 48, "amountOfIngredient": 0.22 },
            { "_id": 224, "mealId": 78, "fridgeItemId": 60, "amountOfIngredient": 0.25 },
            { "_id": 225, "mealId": 79, "fridgeItemId": 50, "amountOfIngredient": 0.08 },
            { "_id": 226, "mealId": 79, "fridgeItemId": 51, "amountOfIngredient": 1 },
            { "_id": 227, "mealId": 79, "fridgeItemId": 61, "amountOfIngredient": 0.03 },
            { "_id": 228, "mealId": 80, "fridgeItemId": 49, "amountOfIngredient": 0.02 },
            { "_id": 229, "mealId": 80, "fridgeItemId": 50, "amountOfIngredient": 0.03 },
            { "_id": 230, "mealId": 80, "fridgeItemId": 51, "amountOfIngredient": 1 },
            { "_id": 231, "mealId": 81, "fridgeItemId": 51, "amountOfIngredient": 1 },
            { "_id": 232, "mealId": 82, "fridgeItemId": 52, "amountOfIngredient": 0.18 },
            { "_id": 233, "mealId": 82, "fridgeItemId": 48, "amountOfIngredient": 0.16 },
            { "_id": 234, "mealId": 83, "fridgeItemId": 74, "amountOfIngredient": 0.3 },
            { "_id": 235, "mealId": 83, "fridgeItemId": 6, "amountOfIngredient": 0.03 },
            { "_id": 236, "mealId": 84, "fridgeItemId": 30, "amountOfIngredient": 0.28 },
            { "_id": 237, "mealId": 84, "fridgeItemId": 63, "amountOfIngredient": 0.05 },
            { "_id": 238, "mealId": 84, "fridgeItemId": 48, "amountOfIngredient": 0.08 },
            { "_id": 239, "mealId": 85, "fridgeItemId": 37, "amountOfIngredient": 0.18 },
            { "_id": 240, "mealId": 86, "fridgeItemId": 73, "amountOfIngredient": 0.12 },
            { "_id": 241, "mealId": 86, "fridgeItemId": 13, "amountOfIngredient": 0.12 },
            { "_id": 242, "mealId": 86, "fridgeItemId": 6, "amountOfIngredient": 0.02 },
            { "_id": 243, "mealId": 87, "fridgeItemId": 67, "amountOfIngredient": 0.16 },
            { "_id": 244, "mealId": 87, "fridgeItemId": 68, "amountOfIngredient": 0.08 },
            { "_id": 245, "mealId": 87, "fridgeItemId": 18, "amountOfIngredient": 0.05 },
            { "_id": 246, "mealId": 88, "fridgeItemId": 17, "amountOfIngredient": 0.12 },
            { "_id": 247, "mealId": 88, "fridgeItemId": 66, "amountOfIngredient": 0.08 },
            { "_id": 248, "mealId": 88, "fridgeItemId": 48, "amountOfIngredient": 0.08 },
            { "_id": 249, "mealId": 89, "fridgeItemId": 75, "amountOfIngredient": 0.24 },
            { "_id": 250, "mealId": 89, "fridgeItemId": 12, "amountOfIngredient": 0.02 },
            { "_id": 251, "mealId": 89, "fridgeItemId": 63, "amountOfIngredient": 0.04 },
            { "_id": 252, "mealId": 90, "fridgeItemId": 76, "amountOfIngredient": 0.18 },
            { "_id": 253, "mealId": 90, "fridgeItemId": 63, "amountOfIngredient": 0.04 },
            { "_id": 254, "mealId": 91, "fridgeItemId": 38, "amountOfIngredient": 0.12 },
            { "_id": 255, "mealId": 91, "fridgeItemId": 32, "amountOfIngredient": 0.04 },
            { "_id": 256, "mealId": 91, "fridgeItemId": 6, "amountOfIngredient": 0.02 },
            { "_id": 257, "mealId": 92, "fridgeItemId": 9, "amountOfIngredient": 1 },
            { "_id": 258, "mealId": 92, "fridgeItemId": 25, "amountOfIngredient": 0.12 },
            { "_id": 259, "mealId": 92, "fridgeItemId": 17, "amountOfIngredient": 0.04 },
            { "_id": 260, "mealId": 93, "fridgeItemId": 3, "amountOfIngredient": 0.14 },
            { "_id": 261, "mealId": 93, "fridgeItemId": 66, "amountOfIngredient": 0.06 },
            { "_id": 262, "mealId": 93, "fridgeItemId": 6, "amountOfIngredient": 0.02 },
            { "_id": 263, "mealId": 94, "fridgeItemId": 35, "amountOfIngredient": 0.14 },
            { "_id": 264, "mealId": 94, "fridgeItemId": 8, "amountOfIngredient": 0.06 },
            { "_id": 265, "mealId": 94, "fridgeItemId": 32, "amountOfIngredient": 0.04 },
            { "_id": 266, "mealId": 95, "fridgeItemId": 36, "amountOfIngredient": 0.14 },
            { "_id": 267, "mealId": 95, "fridgeItemId": 17, "amountOfIngredient": 0.1 },
            { "_id": 268, "mealId": 95, "fridgeItemId": 48, "amountOfIngredient": 0.08 },
            { "_id": 269, "mealId": 96, "fridgeItemId": 53, "amountOfIngredient": 0.14 },
            { "_id": 270, "mealId": 96, "fridgeItemId": 48, "amountOfIngredient": 0.12 },
            { "_id": 271, "mealId": 96, "fridgeItemId": 62, "amountOfIngredient": 1 },
            { "_id": 272, "mealId": 97, "fridgeItemId": 54, "amountOfIngredient": 0.14 },
            { "_id": 273, "mealId": 97, "fridgeItemId": 66, "amountOfIngredient": 0.06 },
            { "_id": 274, "mealId": 97, "fridgeItemId": 6, "amountOfIngredient": 0.02 },
            { "_id": 275, "mealId": 98, "fridgeItemId": 69, "amountOfIngredient": 1 },
            { "_id": 276, "mealId": 98, "fridgeItemId": 17, "amountOfIngredient": 0.1 },
            { "_id": 277, "mealId": 98, "fridgeItemId": 3, "amountOfIngredient": 0.1 },
            { "_id": 278, "mealId": 99, "fridgeItemId": 36, "amountOfIngredient": 0.14 },
            { "_id": 279, "mealId": 99, "fridgeItemId": 48, "amountOfIngredient": 0.1 },
            { "_id": 280, "mealId": 99, "fridgeItemId": 32, "amountOfIngredient": 0.05 },
            { "_id": 281, "mealId": 100, "fridgeItemId": 55, "amountOfIngredient": 1 },
            { "_id": 282, "mealId": 100, "fridgeItemId": 9, "amountOfIngredient": 1 },
            { "_id": 283, "mealId": 100, "fridgeItemId": 17, "amountOfIngredient": 0.03 }
        ],

    Orders:
        [
            { "_id": 1, "mealId": 1, "discount": 0, "amount": 2 },
            { "_id": 2, "mealId": 4, "discount": 10, "amount": 1 },
            { "_id": 3, "mealId": 8, "discount": 0, "amount": 3 },
            { "_id": 4, "mealId": 2, "discount": 0, "amount": 1 },
            { "_id": 5, "mealId": 5, "discount": 5, "amount": 1 },
            { "_id": 6, "mealId": 3, "discount": 0, "amount": 2 },
            { "_id": 7, "mealId": 7, "discount": 0, "amount": 4 },
            { "_id": 8, "mealId": 10, "discount": 0, "amount": 1 },
            { "_id": 9, "mealId": 6, "discount": 15, "amount": 1 },
            { "_id": 10, "mealId": 9, "discount": 0, "amount": 2 }
        ],

    FridgeItems: [
        { "_id": 1, "name": "Tomato", "amount": 50, "typeOfAmount": "kg", "pricePerUnit": 800, "warningAmountPercentage": 10 },
        { "_id": 2, "name": "Mozzarella", "amount": 20, "typeOfAmount": "kg", "pricePerUnit": 3200, "warningAmountPercentage": 5 },
        { "_id": 3, "name": "Chicken Breast", "amount": 30, "typeOfAmount": "kg", "pricePerUnit": 2500, "warningAmountPercentage": 8 },
        { "_id": 4, "name": "Black Pepper", "amount": 5, "typeOfAmount": "kg", "pricePerUnit": 5000, "warningAmountPercentage": 1 },
        { "_id": 5, "name": "Pizza Flour", "amount": 100, "typeOfAmount": "kg", "pricePerUnit": 400, "warningAmountPercentage": 20 },
        { "_id": 6, "name": "Olive Oil", "amount": 25, "typeOfAmount": "l", "pricePerUnit": 4500, "warningAmountPercentage": 5 },
        { "_id": 7, "name": "Frozen Peas", "amount": 15, "typeOfAmount": "kg", "pricePerUnit": 1200, "warningAmountPercentage": 3 },
        { "_id": 8, "name": "Tomato Paste", "amount": 40, "typeOfAmount": "can", "pricePerUnit": 600, "warningAmountPercentage": 10 },
        { "_id": 9, "name": "Burger Buns", "amount": 60, "typeOfAmount": "pcs", "pricePerUnit": 150, "warningAmountPercentage": 15 },
        { "_id": 10, "name": "Cola Syrup", "amount": 10, "typeOfAmount": "l", "pricePerUnit": 2000, "warningAmountPercentage": 2 },
        { "_id": 11, "name": "Fresh Basil", "amount": 6, "typeOfAmount": "kg", "pricePerUnit": 6000, "warningAmountPercentage": 5 },
        { "_id": 12, "name": "Garlic", "amount": 18, "typeOfAmount": "kg", "pricePerUnit": 1400, "warningAmountPercentage": 8 },
        { "_id": 13, "name": "Mushrooms", "amount": 22, "typeOfAmount": "kg", "pricePerUnit": 2100, "warningAmountPercentage": 8 },
        { "_id": 14, "name": "Calamari Rings", "amount": 12, "typeOfAmount": "kg", "pricePerUnit": 4800, "warningAmountPercentage": 6 },
        { "_id": 15, "name": "Spinach", "amount": 14, "typeOfAmount": "kg", "pricePerUnit": 1800, "warningAmountPercentage": 7 },
        { "_id": 16, "name": "Yellow Onion", "amount": 35, "typeOfAmount": "kg", "pricePerUnit": 700, "warningAmountPercentage": 10 },
        { "_id": 17, "name": "Cheddar Cheese", "amount": 16, "typeOfAmount": "kg", "pricePerUnit": 3400, "warningAmountPercentage": 6 },
        { "_id": 18, "name": "Sour Cream", "amount": 10, "typeOfAmount": "l", "pricePerUnit": 1900, "warningAmountPercentage": 8 },
        { "_id": 19, "name": "Tortilla Chips", "amount": 25, "typeOfAmount": "bag", "pricePerUnit": 850, "warningAmountPercentage": 10 },
        { "_id": 20, "name": "Vegetable Stock", "amount": 18, "typeOfAmount": "l", "pricePerUnit": 900, "warningAmountPercentage": 10 },
        { "_id": 21, "name": "Broccoli", "amount": 16, "typeOfAmount": "kg", "pricePerUnit": 1600, "warningAmountPercentage": 8 },
        { "_id": 22, "name": "Pumpkin", "amount": 20, "typeOfAmount": "kg", "pricePerUnit": 950, "warningAmountPercentage": 9 },
        { "_id": 23, "name": "Red Lentils", "amount": 28, "typeOfAmount": "kg", "pricePerUnit": 1100, "warningAmountPercentage": 10 },
        { "_id": 24, "name": "Mixed Seafood", "amount": 14, "typeOfAmount": "kg", "pricePerUnit": 5200, "warningAmountPercentage": 5 },
        { "_id": 25, "name": "Beef Sirloin", "amount": 18, "typeOfAmount": "kg", "pricePerUnit": 5400, "warningAmountPercentage": 6 },
        { "_id": 26, "name": "Duck Breast", "amount": 10, "typeOfAmount": "kg", "pricePerUnit": 6200, "warningAmountPercentage": 5 },
        { "_id": 27, "name": "Pork Loin", "amount": 20, "typeOfAmount": "kg", "pricePerUnit": 3100, "warningAmountPercentage": 7 },
        { "_id": 28, "name": "Lamb Rack", "amount": 9, "typeOfAmount": "kg", "pricePerUnit": 7600, "warningAmountPercentage": 4 },
        { "_id": 29, "name": "Salmon", "amount": 15, "typeOfAmount": "kg", "pricePerUnit": 6900, "warningAmountPercentage": 5 },
        { "_id": 30, "name": "Russet Potatoes", "amount": 45, "typeOfAmount": "kg", "pricePerUnit": 600, "warningAmountPercentage": 12 },
        { "_id": 31, "name": "Pepperoni", "amount": 11, "typeOfAmount": "kg", "pricePerUnit": 4300, "warningAmountPercentage": 6 },
        { "_id": 32, "name": "Parmesan", "amount": 14, "typeOfAmount": "kg", "pricePerUnit": 5100, "warningAmountPercentage": 5 },
        { "_id": 33, "name": "Pizza Sauce", "amount": 20, "typeOfAmount": "l", "pricePerUnit": 1300, "warningAmountPercentage": 8 },
        { "_id": 34, "name": "Pasta Sheets", "amount": 18, "typeOfAmount": "pack", "pricePerUnit": 950, "warningAmountPercentage": 8 },
        { "_id": 35, "name": "Spaghetti", "amount": 26, "typeOfAmount": "kg", "pricePerUnit": 800, "warningAmountPercentage": 10 },
        { "_id": 36, "name": "Penne Pasta", "amount": 24, "typeOfAmount": "kg", "pricePerUnit": 850, "warningAmountPercentage": 10 },
        { "_id": 37, "name": "Arborio Rice", "amount": 20, "typeOfAmount": "kg", "pricePerUnit": 1500, "warningAmountPercentage": 8 },
        { "_id": 38, "name": "Romaine Lettuce", "amount": 16, "typeOfAmount": "kg", "pricePerUnit": 1300, "warningAmountPercentage": 8 },
        { "_id": 39, "name": "Cucumber", "amount": 18, "typeOfAmount": "kg", "pricePerUnit": 900, "warningAmountPercentage": 9 },
        { "_id": 40, "name": "Avocado", "amount": 12, "typeOfAmount": "kg", "pricePerUnit": 3900, "warningAmountPercentage": 6 },
        { "_id": 41, "name": "Tuna", "amount": 10, "typeOfAmount": "kg", "pricePerUnit": 4700, "warningAmountPercentage": 5 },
        { "_id": 42, "name": "Quinoa", "amount": 18, "typeOfAmount": "kg", "pricePerUnit": 2200, "warningAmountPercentage": 8 },
        { "_id": 43, "name": "Shrimp", "amount": 13, "typeOfAmount": "kg", "pricePerUnit": 5600, "warningAmountPercentage": 5 },
        { "_id": 44, "name": "Mascarpone", "amount": 9, "typeOfAmount": "kg", "pricePerUnit": 4200, "warningAmountPercentage": 5 },
        { "_id": 45, "name": "Cocoa Powder", "amount": 6, "typeOfAmount": "kg", "pricePerUnit": 3800, "warningAmountPercentage": 5 },
        { "_id": 46, "name": "Heavy Cream", "amount": 12, "typeOfAmount": "l", "pricePerUnit": 2100, "warningAmountPercentage": 7 },
        { "_id": 47, "name": "Coffee Beans", "amount": 8, "typeOfAmount": "kg", "pricePerUnit": 6200, "warningAmountPercentage": 4 },
        { "_id": 48, "name": "Milk", "amount": 30, "typeOfAmount": "l", "pricePerUnit": 550, "warningAmountPercentage": 10 },
        { "_id": 49, "name": "Tea Leaves", "amount": 5, "typeOfAmount": "kg", "pricePerUnit": 3300, "warningAmountPercentage": 4 },
        { "_id": 50, "name": "Lemon Juice", "amount": 9, "typeOfAmount": "l", "pricePerUnit": 1700, "warningAmountPercentage": 7 },
        { "_id": 51, "name": "Mineral Water Bottles", "amount": 80, "typeOfAmount": "pcs", "pricePerUnit": 180, "warningAmountPercentage": 15 },
        { "_id": 52, "name": "Berry Mix", "amount": 14, "typeOfAmount": "kg", "pricePerUnit": 3400, "warningAmountPercentage": 6 },
        { "_id": 53, "name": "Pancake Mix", "amount": 18, "typeOfAmount": "kg", "pricePerUnit": 900, "warningAmountPercentage": 9 },
        { "_id": 54, "name": "Fish Fillet", "amount": 16, "typeOfAmount": "kg", "pricePerUnit": 4200, "warningAmountPercentage": 6 },
        { "_id": 55, "name": "Hot Dog Sausages", "amount": 40, "typeOfAmount": "pcs", "pricePerUnit": 220, "warningAmountPercentage": 12 },
        { "_id": 56, "name": "Pineapple", "amount": 12, "typeOfAmount": "kg", "pricePerUnit": 1800, "warningAmountPercentage": 6 },
        { "_id": 57, "name": "Prosciutto", "amount": 8, "typeOfAmount": "kg", "pricePerUnit": 6900, "warningAmountPercentage": 4 },
        { "_id": 58, "name": "Cream Cheese", "amount": 10, "typeOfAmount": "kg", "pricePerUnit": 3600, "warningAmountPercentage": 6 },
        { "_id": 59, "name": "Apples", "amount": 18, "typeOfAmount": "kg", "pricePerUnit": 1100, "warningAmountPercentage": 8 },
        { "_id": 60, "name": "Orange Juice Base", "amount": 15, "typeOfAmount": "l", "pricePerUnit": 2400, "warningAmountPercentage": 6 },
        { "_id": 61, "name": "Granulated Sugar", "amount": 25, "typeOfAmount": "kg", "pricePerUnit": 700, "warningAmountPercentage": 10 },
        { "_id": 62, "name": "Eggs", "amount": 180, "typeOfAmount": "pcs", "pricePerUnit": 45, "warningAmountPercentage": 15 },
        { "_id": 63, "name": "Butter", "amount": 12, "typeOfAmount": "kg", "pricePerUnit": 2800, "warningAmountPercentage": 6 },
        { "_id": 64, "name": "Ricotta", "amount": 10, "typeOfAmount": "kg", "pricePerUnit": 3300, "warningAmountPercentage": 6 },
        { "_id": 65, "name": "Vanilla Extract", "amount": 4, "typeOfAmount": "l", "pricePerUnit": 8200, "warningAmountPercentage": 4 },
        { "_id": 66, "name": "Breadcrumbs", "amount": 14, "typeOfAmount": "kg", "pricePerUnit": 900, "warningAmountPercentage": 8 },
        { "_id": 67, "name": "Cabbage", "amount": 16, "typeOfAmount": "kg", "pricePerUnit": 750, "warningAmountPercentage": 8 },
        { "_id": 68, "name": "Carrots", "amount": 22, "typeOfAmount": "kg", "pricePerUnit": 800, "warningAmountPercentage": 10 },
        { "_id": 69, "name": "Tortilla Wraps", "amount": 60, "typeOfAmount": "pcs", "pricePerUnit": 120, "warningAmountPercentage": 12 },
        { "_id": 70, "name": "Vanilla Ice Cream", "amount": 14, "typeOfAmount": "kg", "pricePerUnit": 2600, "warningAmountPercentage": 6 },
        { "_id": 71, "name": "Bacon", "amount": 11, "typeOfAmount": "kg", "pricePerUnit": 3900, "warningAmountPercentage": 5 },
        { "_id": 72, "name": "Beetroot", "amount": 15, "typeOfAmount": "kg", "pricePerUnit": 1000, "warningAmountPercentage": 8 },
        { "_id": 73, "name": "Bell Peppers", "amount": 20, "typeOfAmount": "kg", "pricePerUnit": 1500, "warningAmountPercentage": 8 },
        { "_id": 74, "name": "Sweet Potatoes", "amount": 16, "typeOfAmount": "kg", "pricePerUnit": 950, "warningAmountPercentage": 8 },
        { "_id": 75, "name": "Cauliflower", "amount": 14, "typeOfAmount": "kg", "pricePerUnit": 1300, "warningAmountPercentage": 7 },
        { "_id": 76, "name": "Corn Kernels", "amount": 18, "typeOfAmount": "kg", "pricePerUnit": 1200, "warningAmountPercentage": 8 }
    ],
    Counters: [
        { _id: "userId", seq: 0 },
        { _id: "mealId", seq: 0 },
        { _id: "mealCategoryId", seq: 0 },
        { _id: "workHourId", seq: 0 },
        { _id: "workScheduleId", seq: 0 },
        { _id: "ingredientId", seq: 0 },
        { _id: "orderId", seq: 0 },
        { _id: "fridgeItemId", seq: 0 },
    ]
}